#ifndef LV_SYMBOLS_H
#define LV_SYMBOLS_H
#define BOLT "\xef\x83\xa7"
#define BROADCAST_TOWER "\xef\x94\x99"
#define CHECK_CIRCLE "\xef\x81\x98"
#define CHECK_SQUARE "\xef\x85\x8a"
#define CHEVRON_DOWN "\xef\x81\xb8"
#define CHEVRON_UP "\xef\x81\xb7"
#define CHEVRON_LEFT "\xef\x81\x93"
#define CIRCLE "\xef\x84\x91"
#define MICROCHIP "\xef\x8b\x9b"
#define PLUG "\xef\x87\xa6"
#define RESISTOR "\xef\xbf\xb2"
#define SQUARE "\xef\x83\x88"
#define SWITCH_CLOSED "\xef\xbf\xb1"
#define SWITCH_OPEN "\xef\xbf\xb0"
#define THERMOMETER_FULL "\xef\x8b\x87"
#define UNLOCK_ALT "\xef\x84\xbe"
#define INFO "\xef\x84\xa9"
#endif
